---
#
# Ansible managed
#
repository:
  description: Install and configure GitLab on your system.
  homepage: https://buluma.github.io/
  topics: gitlab, development, ansible, molecule, tox, playbook
