---
image: "buluma/github-action-molecule:4.0.7"

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  PY_COLORS: 1

molecule:
  script:
    - image=${image} tag=${tag} molecule test
  retry: 1
  parallel:
    matrix:
      - image: "enterpriselinux"
        tag: "7"
      - image: "enterpriselinux"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "focal"
      - image: "ubuntu"
        tag: "20.04"
      - image: "ubuntu"
        tag: "18.04"

testing:
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "testing"
  retry: 1
  parallel:
    matrix:
      - image: "enterpriselinux"
        tag: "7"
      - image: "enterpriselinux"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "focal"

galaxy:
  script:
    - ansible-galaxy role info buluma.gitlab

role_testing:
  script:
    - image=${image} tag=${tag} ansible-galaxy install buluma.gitlab
  retry: 1
  parallel:
    matrix:
      - image: "enterpriselinux"
        tag: "7"
      - image: "enterpriselinux"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "focal"
