---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check gitlab-runsvdir service
      ansible.builtin.service:
        name: gitlab-runsvdir
      check_mode: yes
      register: gitlab_service_check
      failed_when:
        - gitlab_service_check is changed

    - name: check gitlab status
      ansible.builtin.command:
        cmd: gitlab-ctl status
      changed_when: no

    - name: see if web interface can be used
      ansible.builtin.uri:
        url: http://127.0.0.1/users/sign_in

    - name: read initial_root_password file
      slurp:
        src: /etc/gitlab/initial_root_password
      register: initial_root_password
      when:
        - gitlab_initial_root_password | bool

    - name: Extract Password from variable initial_root_password
      set_fact:
        gitlab_password: "{{ initial_root_password['content'] | b64decode | regex_search('Password: (.+)', '\\1') | first }}"
      when:
        - gitlab_initial_root_password | bool

    - name: Print gitlab password
      debug:
        var: gitlab_password
      when:
        - gitlab_initial_root_password | bool
