---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check gitlab-runsvdir service
      ansible.builtin.service:
        name: gitlab-runsvdir
      check_mode: yes
      register: gitlab_service_check
      failed_when:
        - gitlab_service_check is changed

    - name: check gitlab status
      ansible.builtin.command:
        cmd: gitlab-ctl status
      changed_when: no

    - name: see if web interface can be used
      ansible.builtin.uri:
        url: http://127.0.0.1/users/sign_in

    - name: Get stats of the initial_root_password object
      ansible.builtin.stat:
        path: /etc/gitlab/initial_root_password
      register: p
    - name: Print a debug message
      ansible.builtin.debug:
        msg: "Path exists and is a file"
      when: p.stat.isdir is defined and p.stat.isdir
